import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.NEXT_PUBLIC_GEMINI_API_KEY || '');

export interface VerificationQuestion {
  id: number;
  question: string;
}

export interface EvaluationResult {
  score: number;
  feedback: string;
  isHuman: boolean;
  aiProbability: number;
}

export async function generateSkillQuestions(skill: string): Promise<VerificationQuestion[]> {
  const model = genAI.getGenerativeModel({ model: 'gemini-3-flash-preview' });
  
  const prompt = `Generate 5 intermediate to hard technical short-answer questions to verify someone's expertise in "${skill}".
  Return the response as a JSON array of objects, each with "id" and "question" keys.
  Do not include any other text or formatting. Use the following format:
  [
    {"id": 1, "question": "..."},
    {"id": 2, "question": "..."},
    ...
  ]`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    // Simple JSON extraction to handle potential markdown formatting from AI
    const jsonMatch = text.match(/\[.*\]/s);
    if (!jsonMatch) throw new Error("Failed to parse questions from Gemini");
    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
}

export async function evaluateSkillAnswers(
  skill: string, 
  questions: VerificationQuestion[], 
  answers: string[]
): Promise<EvaluationResult> {
  const model = genAI.getGenerativeModel({ model: 'gemini-3-flash-preview' });
  
  const prompt = `Evaluate the following technical answers for the skill "${skill}".
  Analyze both technical correctness and the likelihood that the answers were generated by another AI (check for typical AI patterns, overly structured responses, or generic Wikipedia-style writing).

  Questions and Answers:
  ${questions.map((q, i) => `Q${i+1}: ${q.question}\nA${i+1}: ${answers[i]}`).join('\n\n')}

  Return the response as a JSON object with these keys:
  - "score": (number 0-100 summarizing technical accuracy)
  - "feedback": (string providing constructive feedback)
  - "isHuman": (boolean, true if the answers seem written by a human)
  - "aiProbability": (number 0-1, where 1 is definitely AI)

  Format:
  {"score": 85, "feedback": "...", "isHuman": true, "aiProbability": 0.1}`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    const jsonMatch = text.match(/\{.*\}/s);
    if (!jsonMatch) throw new Error("Failed to parse evaluation from Gemini");
    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error("Gemini Evaluation Error:", error);
    throw error;
  }
}
